# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Frame2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class UI2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(924, 495)
        self.titleLogo = QtWidgets.QLabel(Form)
        self.titleLogo.setGeometry(QtCore.QRect(20, 20, 271, 51))
        self.titleLogo.setStyleSheet("image: url(:/Labels/ManageCraft.png);")
        self.titleLogo.setText("")
        self.titleLogo.setObjectName("titleLogo")
        self.restartBtn = QtWidgets.QPushButton(Form)
        self.restartBtn.setGeometry(QtCore.QRect(810, 30, 101, 31))
        self.restartBtn.setStyleSheet("border-image: url(:/Buttons/RSTButtonUnchecked.png);\n"
"border-image: url(:/Buttons/Restart.png);\n"
"")
        self.restartBtn.setText("")
        self.restartBtn.setObjectName("restartBtn")
        self.stopBtn = QtWidgets.QPushButton(Form)
        self.stopBtn.setGeometry(QtCore.QRect(710, 30, 101, 31))
        self.stopBtn.setStyleSheet("border-image: url(:/Buttons/Stop.png);")
        self.stopBtn.setText("")
        self.stopBtn.setObjectName("stopBtn")
        self.startBtn = QtWidgets.QPushButton(Form)
        self.startBtn.setGeometry(QtCore.QRect(610, 30, 101, 31))
        self.startBtn.setStyleSheet("border-image: url(:/Buttons/Start.png);")
        self.startBtn.setText("")
        self.startBtn.setObjectName("startBtn")
        self.lefty = QtWidgets.QWidget(Form)
        self.lefty.setGeometry(QtCore.QRect(30, 90, 351, 351))
        self.lefty.setStyleSheet("border-image: url(:/Buttons/F2Box.png); background-repeat: no-repeat;")
        self.lefty.setObjectName("lefty")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.lefty)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.lefty)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 324, 418))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.aLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.aLabel.setObjectName("aLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.aLabel)
        self.aLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.aLineEdit.setStyleSheet("border-image: white;")
        self.aLineEdit.setObjectName("aLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.aLineEdit)
        self.bLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.bLabel.setObjectName("bLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bLabel)
        self.bLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.bLineEdit.setObjectName("bLineEdit")
        self.bLineEdit.setStyleSheet("border-image: white;")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bLineEdit)
        self.cLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.cLabel.setObjectName("cLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cLabel)
        self.cLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.cLineEdit.setObjectName("cLineEdit")
        self.cLineEdit.setStyleSheet("border-image: white;")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cLineEdit)
        self.aLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.aLabel_2.setObjectName("aLabel_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.aLabel_2)
        self.aDial = QtWidgets.QDial(self.scrollAreaWidgetContents)
        self.aDial.setObjectName("aDial")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.aDial)
        self.bLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.bLabel_2.setObjectName("bLabel_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.bLabel_2)
        self.bDial = QtWidgets.QDial(self.scrollAreaWidgetContents)
        self.bDial.setObjectName("bDial")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.bDial)
        self.cLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.cLabel_2.setObjectName("cLabel_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.cLabel_2)
        self.cDial = QtWidgets.QDial(self.scrollAreaWidgetContents)
        self.cDial.setObjectName("cDial")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cDial)
        self.dLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.dLabel.setObjectName("dLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.dLabel)
        self.dLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.dLineEdit.setObjectName("dLineEdit")
        self.dLineEdit.setStyleSheet("border-image: white;")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dLineEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.saveBtn = QtWidgets.QPushButton(self.lefty)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveBtn.sizePolicy().hasHeightForWidth())
        self.saveBtn.setSizePolicy(sizePolicy)
        self.saveBtn.setObjectName("saveBtn")
        self.verticalLayout.addWidget(self.saveBtn)
        self.righty = QtWidgets.QWidget(Form)
        self.righty.setGeometry(QtCore.QRect(530, 90, 380, 380))
        self.righty.setStyleSheet("border-image: url(:/Buttons/F2Box.png); background-repeat: no-repeat;")
        self.righty.setObjectName("righty")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.aLabel.setText(_translate("Form", "a"))
        self.bLabel.setText(_translate("Form", "b"))
        self.cLabel.setText(_translate("Form", "c"))
        self.aLabel_2.setText(_translate("Form", "A"))
        self.bLabel_2.setText(_translate("Form", "B"))
        self.cLabel_2.setText(_translate("Form", "C"))
        self.dLabel.setText(_translate("Form", "d"))
        self.saveBtn.setText(_translate("Form", "SAVE"))
import Logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = UI2()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
